# Generated by Django 5.0.3 on 2024-04-22 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0006_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('Buyer_Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Date_Of_Birth', models.CharField(blank=True, max_length=100, null=True)),
                ('Location', models.CharField(max_length=100)),
                ('Phone_Number', models.IntegerField(null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('Seller_Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Date_Of_Birth', models.CharField(blank=True, max_length=100, null=True)),
                ('Location', models.CharField(max_length=100)),
                ('Phone_Number', models.IntegerField(null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Amount', models.IntegerField(null=True)),
                ('Buyer_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.buyer')),
                ('Product_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
                ('Seller_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Payment_Amount', models.IntegerField(null=True)),
                ('Payment_Option', models.CharField(choices=[('Bkash', 'Bkash'), ('Rocket', 'Rocket'), ('Nogod', 'Nogod')], max_length=100, null=True)),
                ('Payment_Time', models.TimeField(auto_now_add=True)),
                ('Payment_Date', models.DateTimeField(auto_now_add=True)),
                ('Order_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.order')),
            ],
        ),
        migrations.CreateModel(
            name='Sell_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
                ('Seller_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Price', models.IntegerField(null=True)),
                ('Product_Amount', models.IntegerField(null=True)),
                ('Product_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
                ('Seller_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.seller')),
            ],
        ),
    ]
