# Generated by Django 5.0.3 on 2024-04-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='buyer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
    ]
