# Generated by Django 5.0.3 on 2024-04-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_alter_cart_buyer_id_alter_cart_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Buyer_Id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Seller_Id',
            field=models.IntegerField(null=True),
        ),
    ]
