# Generated by Django 5.1.6 on 2025-04-14 08:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_cart_quantity'),
        ('dashboard', '0007_product_description_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Product_Amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Product_Id',
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Total_Amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='buyer.order')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
        ),
    ]
